Ecto migration / Context 구현
27672f75-6a84-45d8-808e-754f96daa437/blog_umbrella pull request #1
Opened 2022-10-17 09:06 UTC by twozeronine

# Ecto migration / Context 구현

## migration 내용

### user
- user_email
- user_name
- password // virtual
- password_hash

### post
- title
- description
- belongs_to(:user)
- has_many(:comments)

### comments
- description
- user_name // virtual
- belongs_to(:user)
- belongs_to(:post)

## Context 구현

### Accounts

user 의 CRUD 구현

### Boards

post CRUD 구현
comment CRUD 구현

2022-10-17 16:36 UTC, rudebono requested changes
ecto 책 다시 보면서 `cast_assoc` 에 대해 다시 공부한 후에 코드를 수정해주세요.
마이그레이션은 잘 하였지만, 스키마와 컨텍스트는 `cast_assoc` 추가한 후에 리뷰할 수 있습니다.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/priv/repo/migrations/20221016122036_create_users.exs
> +      add(:password_hash, :string, [{:null, false}])
`:string`은 기존적으로 [255자](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#add/3-options)가 max 입니다.
만약에 패스워드 암호화 함수를 사용한 후 나오는 값이 255자가 넘는다면
`:text`를 사용하면 됩니다.

현재 사용하는 `:argon2_elixir`의 기존 config값은 97자가 나오기 떄문에 신경안써도 될것같네요.

`:argon2_elixir` config에는 암호화 결과의 길이를 더 길게, round를 늘려서 더 강력하게, CPU Thread를 늘려서 모든 하드웨어 리소스를 사용하여 더 빠르게 등 설정할 수 있습니다. 시간날때 다양한 옵션을 보면서 암호화에 어떻 옵션들이 있는지 살펴보는게 좋습니다.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/priv/repo/migrations/20221017030846_create_posts.exs
> +      add :user_id, references(:users, on_delete: :nothing)
add() 넣어주세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/priv/repo/migrations/20221017030846_create_posts.exs
> +    create index(:posts, :user_id)
`:posts`를 `@table`로 변경해주세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/priv/repo/migrations/20221017061514_create_comment.exs
> +    create index(:comments, :user_id)
`:comments`를 `@table`로 변경해주세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/priv/repo/migrations/20221017061514_create_comment.exs
> +      add :post_id, references(:posts, on_delete: :delete_all)
이번 프로젝트에서는
`on_delete:`의 일괄성을 유지해주세요.
`:nothing` or `:delete_all` 둘 중 하나만 선택해주세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/priv/repo/migrations/20221017061514_create_comment.exs
> +      add :user_id, references(:users, on_delete: :nothing)
add() 괄호를 넣어주세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts/user.ex
> +    IO.inspect(changeset)
`IO.inspect/1` 빼주세요. 날 조커로 만들지 말아주세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts/user.ex
> +  def user_id_query(query, %__MODULE__{id: user_id}) do
- `def user_id_query(query, %__MODULE__{id: user_id}) do`
- `def user_id_query(query, %{id: user_id}) do`
- `def user_id_query(query, user_id) do`

셋다 가능합니다. 이 함수를 사용하는 쪽에서 편한걸 선택하면됩니다.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/boards/post.ex
> +  def post_id_query(query, %__MODULE__{id: post_id}) do
- `def post_id_query(query, %__MODULE__{id: post_id}) do`
- `def post_id_query(query, %{id: post_id}) do`
- `def post_id_query(query, post_id) do`

셋다 가능합니다. 이 함수를 사용하는 쪽에서 편한걸 선택하면됩니다.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts/user.ex
> +
```elixir
has_many(:posts, BlogDomain.Boards.Post)
has_many(:comments, BlogDomain.Boards.Comment)
```

이걸 추가해도 괜찮을것같네요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts/user.ex
> +    |> validate_length(:password, [{:min, 8}, {:max, 128}])
[`cast_assoc`](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3) 를 추가하여,
User의 changeset을 만들때 Post, Comment 도 함께 cast하여 insert or update 할수 있습니다.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts.ex
> +  def create_user!(params \\ %{}) do
! 함수는 제거하세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts.ex
> +  def update_username(id, %{user_name: user_name, password: password}) do
`def update_username` 에서 password를 체크하지 않아도 됩니다.
변경될 User의 권한이 있는지는 phoenix 단에서 검증해서 권한이있으면 호출하고 아니면 오류를 내면 됩니다.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts.ex
> +  def delete_user(id) do
delete는 lock 안걸어도 괜찮습니다.
만약에 하고 싶으면

```elixir
id
|> get_user_lock()
|> Repo.delete()
```

이런식으로 코드를 정리해주세요.

2022-10-17 16:36 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/boards.ex
> +    |> Ecto.Changeset.put_assoc(:user, user)
Ecto.Changeset.put_assoc 를 여기서 사용하면 안되고 스키마단계에서 해야합니다.
changeset에 [cast_assoc](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3) 를 추가하세요.

- `BlogDomain.Boards`
- `BlogDomain.Boards.Post`
- `BlogDomain.Boards.Comment`
- 
위 코드들에서 `cast_assoc`를 사용하지 않아서 모두 다시 작성해야합니다.

2022-10-18 16:44 UTC, rudebono requested changes
이번 코드 리뷰 중점 포인트

1. `cast_assoc` 추가하여 불가능한 코드는 [`put_assoc`](https://hexdocs.pm/ecto/Ecto.Changeset.html#put_assoc/4) 를 사용하면 된다. 어떤 로직을 만드느냐에 따라 어떤걸 사용할지는 모르지만, 스키마 모듈의 changeset에 넣는건 동일하다.
2. user의 password virtual은 insert할때 필요했고, comment의 username 같은 경우 get할때 필요한것이다. virtual의 사용법이 다르기 때문에 스키마에서 virtual를 cast할지 말지 잘 선택해라.
3. lock: "FOR UPADTE", preload 모두 [query](https://hexdocs.pm/ecto/Ecto.Query.html#preload/3)로 만들어서 스키마에 넣을 수 있다.

2022-10-18 16:44 UTC, rudebono commented on apps/blog/mix.exs
>    # Type `mix help deps` for examples and options.
comment 지우세요.

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts.ex
> +  def update_username(id, %{user_name: user_name}) do
```elixir
def update_user(user_id, params) do
```

로 했을 경우 범용성을 지키면서, 여러 파라미터를 받을 수 있습니다.

```elixir
def update_username(id, name) do
```
username만 변경하는 경우 `map`으로 받을 필요 없을것같네요.

```elixir
def update_user(%User{} = user, params) do
```
도 좋아보입니다.

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/accounts.ex
> +      user = get_user_lock(id)
```elixir
id
|> get_user_lock()
|> ...
```

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/application.ex
>      opts = [strategy: :one_for_one, name: BlogDomain.Supervisor]
```elixir
[strategy: :one_for_one, name: __MODULE__]
```

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/boards.ex
> +  def create_post(%User{} = user, params \\ %{}) do
```elixir
def create_post(%User{id: user_id}, params \\ %{}) do
```

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/boards.ex
> +    get_user_post(user, post_id, lock: "FOR UPDATE")
참고로 lock도 query로 만들어서 `BlogDomain.Boards.Post` 모듈안에 함수로 옮길 수 있습니다.

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/boards.ex
> +  def write_comment(%Accounts.User{id: user_id, user_name: user_name}, post_id, params \\ %{}) do
```elixir
def write_comment(%User{id: user_id, user_name: user_name}, post_id, params \\ %{}) do
```

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/boards.ex
> +    |> Comment.changeset(Map.put(params, :user_name, user_name))
:user_name은 virtual이라서 changeset의 cast에 사용하지 않습니다.
잘못된 사용 방법입니다.

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/lib/blog_domain/boards/comment.ex
> +    |> cast(params, [:description, :user_name, :user_id, :post_id])
virtual의 예)

```elixir
  schema "partners" do
    belongs_to(:user, User, foreign_key: :id, primary_key: true, define_field: false)
    many_to_many(:orgs, Org, join_through: PartnerOrg)

    field(:name, :string, virtual: true)
    field(:email, :string, virtual: true)
    field(:current_org, :map, virtual: true)
    field(:roles, {:array, :string}, virtual: true)
  end

  @required [:id]
  def changeset(%__MODULE__{} = struct, attrs) do
    struct
    |> cast(attrs, @required)
    |> validate_required(@required)
  end

  def get(id) do
    from q in __MODULE__,
      where: q.id == ^id,
      join: u in assoc(q, :user),
      select: %__MODULE__{q | name: u.name, email: u.email}
  end
```

2022-10-18 16:44 UTC, rudebono commented on apps/blog_domain/priv/repo/seeds.exs
> +# alias BlogDomain.Boards
comment 지우기.

2022-10-19 03:10 UTC, twozeronine commented on apps/blog/mix.exs
>    # Type `mix help deps` for examples and options.
blog_api에 있는 주석은 phoenix router / controller 작업시에 다 지우고 시작하겠습니다 !

2022-10-19 03:27 UTC, twozeronine commented on apps/blog_domain/priv/repo/seeds.exs
> +# alias BlogDomain.Boards
주석 지우기 완료하였고, 

blog_api에 있는 주석은 phoenix router / controller 작업시에 다 지우고 시작하겠습니다 !

2022-10-19 03:30 UTC, twozeronine commented on apps/blog_domain/lib/blog_domain/boards/comment.ex
> +    |> cast(params, [:description, :user_name, :user_id, :post_id])
제가 원하던 방법이 이거였습니다! 

댓글 불러올시 user_name을 불러와 댓글 내용과 user_name을 view에서 표시하고싶었습니다.

 참고 하겠습니다

2022-10-19 03:38 UTC, twozeronine commented on apps/blog_domain/lib/blog_domain/accounts.ex
> +  def update_username(id, %{user_name: user_name}) do
참고하겠습니다

2022-10-19 06:36 UTC, twozeronine commented on apps/blog/lib/blog/application.ex
>      Supervisor.start_link(children, strategy: :one_for_one, name: Blog.Supervisor)
수정완료했습니다 ! blog_api는 작업시 주석 제거 및 컨벤션 진행하겠습니다.

2022-10-19 07:00 UTC, rudebono approved these changes
LGTM

2022-10-19 07:03 UTC, merged