Blog client
27672f75-6a84-45d8-808e-754f96daa437/blog_umbrella pull request #3
Opened 2022-10-20 16:11 UTC by twozeronine

# HTTPoison Client

HTTPoison으로 구현한 클라이언트입니다 !

2022-10-21 01:10 UTC, rudebono requested changes
Remove `GenServer`

2022-10-21 02:00 UTC, rudebono requested changes
이번 리뷰 핵심 : 코드 분리, 중복 제거, config 활용

2022-10-21 02:00 UTC, rudebono commented on apps/blog_client/lib/blog_client.ex
> +  @api_url "http://localhost:4000/api"
1. `@api_url` 는 config 로 옮기기
2. `@users_url`, `@posts_url` 은 제거하여 path만 남기기

2022-10-21 02:00 UTC, rudebono commented on apps/blog_client/lib/blog_client.ex
> +  defp comments_url(post_id), do: "#{@posts_url}/#{post_id}/comments"
이런건 별도로 함수를 안만들어도됨

2022-10-21 02:00 UTC, rudebono commented on apps/blog_client/lib/blog_client.ex
> +  def register_user(
1. `.Api` 모듈안에 Params를 생성하는 함수를 별도로 만들어서 분리할 수 있다.

```elixir
defmodule BlogCliant.Api do
  def register_user(user_name, user_email, password) do
    %{user_name: user_name, user_email: user_email, password: password}
  end
end
```

2. .Client 모듈안에 get, post, put .. 과 redner_reponse를 옮겨서 분리.
3. .Client 모듈안에 params로 HTTP 클라이언트 모듈명을 받던지, config로 받아서 언제든지 다른 클라이언트를 사용할 수 있도록 변경

```elixir
defmodule BlogCliant.Client do
def get(path, client \\ HTTPoison) do
  apply(client, :get, [path])
  |> render_response()
end
```

2022-10-24 02:00 UTC, rudebono requested changes

2022-10-24 02:00 UTC, rudebono commented on apps/blog_client/lib/blog_client.ex
> +    IO.inspect(response)
IO.inspect 제거 (콘솔에서 IO.insepct 없이도 확인할 수 있으니 필요없음)

2022-10-24 03:07 UTC, twozeronine commented on apps/blog_client/lib/blog_client.ex
> +    IO.inspect(response)
넵 제거하겠습니다.

2022-10-24 04:50 UTC, rudebono approved these changes
LGTM 🎉

2022-10-24 04:50 UTC, rudebono commented
https://hex.pm/packages/tesla

위 http client 패키지 참고 바람

2022-10-24 06:17 UTC, merged