Authentication
27672f75-6a84-45d8-808e-754f96daa437/blog_umbrella pull request #4
Opened 2022-10-24 06:23 UTC by twozeronine

## 새로 추가된 라우터

auth 자격이 있어야 user의 목록을 볼수도록 라우터를 수정하였고

기존 user에 있던 create와 login 함수를 auth의 register login 함수로 변경했습니다.

```
user_path     GET       /api/auth/users            BlogApi.UserController :index

auth_path     POST      /api/register              BlogApi.AuthController :register
auth_path     POST      /api/login                 BlogApi.AuthController :login
```

2022-10-24 07:30 UTC, rudebono requested changes
BlogApi.Auth, BlogApi.Token 다시 하셈

2022-10-24 09:24 UTC, rudebono requested changes

2022-10-24 09:24 UTC, rudebono commented on apps/blog_api/lib/blog_api/token.ex
> +  defp signer_create() do
동사가 앞으로 `create_signer`

2022-10-24 15:37 UTC, rudebono requested changes

2022-10-24 15:37 UTC, rudebono commented on apps/blog_api/lib/blog_api/token.ex
> +defmodule BlogApi.Token do
JWT, Joken에 대한 이해가 없이 사용되어 리뷰 불가능함.
아래와 같이 사용해보고 이해해보기.

1. `BlogApi.Token`을 `Blog.Token`으로 옮기기
2. `use Joken.Config` 후 어떠한 함수를 생성하지말기
3. 매크로로 만들어진 `Blog.Token.generate_and_sign/1`, `BlogApi.Token.verify_and_validate/1`  사용해보기

2022-10-24 15:37 UTC, rudebono commented on apps/blog_api/lib/blog_api/auth.ex
> +  def login(conn, %User{id: user_id}) do
1. `import Plug.Conn`를 사용하려면 BlogApi.AuthPlug를 별도로 만들어서 `init`, `call`만 남기기. (Auth와 AuthPlug로 분리가 핵심)

2022-10-24 15:37 UTC, rudebono commented on apps/blog_api/lib/blog_api/controllers/auth_controller.ex
> +defmodule BlogApi.AuthController do
에러 처리 관련 부분 모두 삭제, 모두 성공 케이스만 처리함.

예)
```elixir
case Accounts.create_user(params) do
  {:ok, %User{} = user} -> ...
```

```elixir
{:ok, %User{} = user} = Accounts.create_user(params) 
```

2022-10-25 04:47 UTC, twozeronine commented on apps/blog_api/lib/blog_api/controllers/auth_controller.ex
> +defmodule BlogApi.AuthController do
모든 컨트롤러에서 삭제 완료했습니다 !

2022-10-25 05:00 UTC, rudebono requested changes

2022-10-25 06:14 UTC, rudebono requested changes

2022-10-25 06:14 UTC, rudebono commented on apps/blog_api/lib/blog_api/auth.ex
> +defmodule BlogApi.Auth do
`BlogApi.Auth` 제거 후 `Blog.Token` 을 사용하도록 변경

2022-10-25 06:14 UTC, rudebono commented on apps/blog_api/lib/blog_api/controllers/comment_controller.ex
>    def create(conn, %{"user" => %{"id" => id}, "post_id" => post_id, "comment" => comment_param}) do
`AuthPlug` 통과 후 사용하는 모든 컨트롤러에서 `"user" => %{"id" => id}` 를 Params로 받지말고,
헤더에서 토큰을 가져온 후 토큰을 까서 user_id를 가져오도록 변경

2022-10-25 07:22 UTC, rudebono approved these changes
LGTM

2022-10-25 07:29 UTC, merged